### ISSUE TITLE
This project does not have enough video or examples 

### ISSUE THREAD

**Issue by SigireddyBalasai** [SigireddyBalasai/whatpack.py#1]
i need help in this young and enthusiastic contributors

**Comment by SigireddyBalasai** [comment]
@29deepanshutyagi  sure but i want to say don't go too big and make a large pr do it small i will agree small contributions also don't get stressed just take it easy and do it efficiently

**Comment by Parvezkhan0** [comment]
I want to work on this issue. Please assign it to me

**Comment by SigireddyBalasai** [comment]
Bro you are free to make any non code contribution even code as well as the issue is already assigned i cannot reassign to you if there is no commit from our brother for two days then I will reassign in mean time you can raise issues

**Comment by SigireddyBalasai** [comment]
@Parvezkhan0 assigned
